version: "3.8"

services:
  employee-app:
    build: ./
    command: ./wait-for-postgres.sh db postgres ./smartway-employee-app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=admin
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5436:5432